### ISSUE TITLE
Reverse order

### ISSUE THREAD

**Issue by jlarmstrongiv** [camsteffen/compear#1]
I noticed you had a reverse function for your tests—it would be nice to have a reverse order for the comparison functions too.  Fun library!  Fun name!  Thank you for making it.

**Comment by camsteffen** [comment]
Hi, thanks for taking interest in compear, and congrats on opening issue \# 1! 😄

I figured this question might come up. You are talking about this [reverse function](https://github.com/camsteffen/compear/blob/40ae7316c506cd8b50f2b3187da331280773d748/src/private/reverse.ts#L3), right? Yes, this could easily be part of the public API. But there is also `compareByDesc` and `reverseOrder`, and I suspect those will be sufficient for a large majority of use cases. And I believe these functions should be better for readability. But I'm open to re-considering it if someone can show an example where a reverse function seems needful.

I would probably name the function `reverseComparator` instead of `reverse` if it were public.

**Comment by jlarmstrongiv** [comment]
That’s the one!  I had somehow missed `reverseOrder`, which is what I needed.  Thank you camsteffen 😄
